// build_static.cjs —— 从 optimized/dist/p3_2_client.js 生成静态插件 lib/client.js
// 用法: node build_static.cjs <源文件> <目标文件>
// 源文件约定（optimized/dist/p3_2_client.js，由 build.cjs 生成）:
//   module.exports = { clientBodyP31, hostBodyP31 }
// 常规构建链：node optimized\build.cjs && node build_static.cjs optimized\dist\p3_2_client.js lib\client.js
const fs = require('fs')
const path = require('path')

const [srcArg, dstArg] = process.argv.slice(2)
if (!srcArg || !dstArg) {
  console.error('usage: node build_static.cjs <src> <dst>')
  process.exit(1)
}
const srcPath = path.resolve(srcArg)
const dstPath = path.resolve(dstArg)
const mod = require(srcPath)
const fnName = Object.keys(mod).find((k) => k.startsWith('clientBody'))
if (!fnName) {
  console.error('no clientBodyXxx export found in', srcPath)
  process.exit(1)
}

const body = mod[fnName].toString() // "function clientBodyP31() { return { ... }, }"
const prefix = body.slice(0, body.indexOf('{')) + '{' // "function clientBodyP31() {"
const innerRaw = body.slice(prefix.length).trim()      // "return { ... },\n}"
const inner = innerRaw.slice(0, innerRaw.lastIndexOf('}')) // "return { ... },"
const obj = inner.replace(/^return\s*/, '').replace(/,\s*$/, '').trim() // "{ ... }"

const client = `// Generated by build_static.cjs from ${path.basename(srcPath)} (${fnName}).
// Static bundle for the dsh web client module system.
// Do not edit by hand; regenerate with: node build_static.cjs <src> <dst>
window.__ModuleLoader__.load({
  id: "dsh-theme-customizer",
  factory: (require) => {
    const module = { exports: {} }
    const exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" })
    const React = require("react")
    const plugin = ${obj}
    exports.apply = plugin.apply
    exports.inject = ["slots", "theme"]
    return module.exports
  },
})
`
fs.writeFileSync(dstPath, client, 'utf8')
console.log('written', dstPath, client.length, 'chars')
